name: Publish technical documentation
description: |
  This action syncs the documentation to the website repository where it is published on the website.

  You need the following permissions on the workflow to fetch secrets from Vault needed by this action.

  ```yaml
  permissions:
    contents: read
    id-token: write
  ```
inputs:
  source_directory:
    default: docs/sources
    description: Path to source directory, relative to the project root, to sync documentation from.
  website_directory:
    description: Website directory to sync the documentation to.
    required: true
runs:
  using: composite
  steps:
    - name: Build website
      shell: bash
      run: |
        docker run -v "${PWD}/${{ inputs.source_directory }}:/hugo/${{ inputs.website_directory }}" --rm grafana/docs-base:latest /bin/bash -c 'make hugo'

    - id: get-secrets
      uses: grafana/shared-workflows/actions/get-vault-secrets@main
      with:
        common_secrets: |
          PUBLISH_TECHNICAL_DOCUMENTATION_APP_ID=docs-team/publish-technical-documentation:app-id
          PUBLISH_TECHNICAL_DOCUMENTATION_PRIVATE_KEY=docs-team/publish-technical-documentation:key

    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ env.PUBLISH_TECHNICAL_DOCUMENTATION_APP_ID }}
        owner: grafana
        private-key: ${{ env.PUBLISH_TECHNICAL_DOCUMENTATION_PRIVATE_KEY }}

    - name: Checkout sync action
      uses: actions/checkout@v4
      with:
        path: .github/actions/website-sync
        repository: grafana/website-sync
        token: ${{ steps.app-token.outputs.token }}

    - name: Sync to the website repository
      uses: ./.github/actions/website-sync
      id: publish
      with:
        allow_no_changes: true
        repository: grafana/website
        branch: master
        host: github.com
        github_pat: grafanabot:${{ steps.app-token.outputs.token }}
        source_folder: ${{ inputs.source_directory }}
        target_folder: ${{ inputs.website_directory }}
