name: Publish technical documentation
description: |
  This action syncs the documentation to the website repository where it is published on the website.

  You need the following permissions on the workflow to fetch secrets from Vault needed by this action.

  ```yaml
  permissions:
    contents: read
    id-token: write
  ```
inputs:
  source-directory:
    default: docs/sources
    description: Path to source directory, relative to the project root, to sync documentation from.
  website-directory:
    description: Website directory to sync the documentation to.
    required: true
runs:
  using: composite
  steps:
    - name: Build website
      shell: bash
      run: |
        docker run -v "${PWD}/${{ inputs.source-directory }}:/hugo/${{ inputs.website-directory }}" --rm grafana/docs-base:latest /bin/bash -c 'make hugo'

    - id: get-secrets
      uses: grafana/shared-workflows/actions/get-vault-secrets@main
      with:
        common_secrets: |
          PUBLISH_TECHNICAL_DOCUMENTATION_APP_ID=docs-team/publish-technical-documentation:app-id
          PUBLISH_TECHNICAL_DOCUMENTATION_PRIVATE_KEY=docs-team/publish-technical-documentation:key

    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ env.PUBLISH_TECHNICAL_DOCUMENTATION_APP_ID }}
        private-key: ${{ env.PUBLISH_TECHNICAL_DOCUMENTATION_PRIVATE_KEY }}

    - uses: actions/checkout@v4
      with:
        path: website
        repository: grafana/website
        sparse-checkout: |
          content/docs
        token: ${{ steps.app-token.outputs.token }}

    - name: Sync to the website repository
      uses: actions/github-script@v7
      with:
        script: |
          const { main } = await import('${{ github.action_path }}/dist/action.mjs');

          await main();
        source-directory: ${{ inputs.source-directory }}
        token: ${{ steps.app-token.outputs.token }}
        website-directory: ${{ inputs.website-directory }}
