name: Publish technical documentation
description: |
  This action syncs the documentation to the website repository where it is published on the website.

  You need the following permissions on the workflow to fetch secrets from Vault needed by this action.

  ```yaml
  permissions:
    contents: read
    id-token: write
  ```
inputs:
  source_directory:
    default: docs/sources
    description: Path to source directory, relative to the project root, to sync documentation from.
  website_directory:
    description: Website directory to sync the documentation to.
    required: true
runs:
  using: composite
  steps:
    - name: Build website
      shell: bash
      run: |
        docker run -v "${PWD}/${{ inputs.source_directory }}:/hugo/${{ inputs.website_directory }}" --rm grafana/docs-base:latest /bin/bash -c 'make hugo'

    - id: get-secrets
      uses: grafana/shared-workflows/actions/get-vault-secrets@main
      with:
        # sync-token and publish-token are fine-grained GitHub Personal Access Tokens that expire.
        # They must be updated in the grafanabot GitHub account.
        # A Vault admin can add them the ci/common/docs-team/website Vault path.
        common_secrets: |
          WEBSITE_SYNC_TOKEN=docs-team/website:sync-token
          PUBLISH_TO_WEBSITE_TOKEN=docs-team/website:publish-token

    - name: Checkout sync action
      uses: actions/checkout@v4
      with:
        path: .github/actions/website-sync
        repository: grafana/website-sync
        token: ${{ env.WEBSITE_SYNC_TOKEN }}

    - name: Sync to the website repository
      uses: ./.github/actions/website-sync
      id: publish
      with:
        repository: grafana/website
        branch: master
        host: github.com
        github_pat: grafanabot:${{ env.PUBLISH_TO_WEBSITE_TOKEN }}
        source_folder: ${{ inputs.source_directory }}
        target_folder: ${{ inputs.website_directory }}
