name: Run Vale
description: |
  Lints documentation with Vale.

  Note that the action assumes you are running the steps using the grafana/vale container image.
inputs:
  directory:
    default: docs/sources
    description: Directory containing documentation for linting.
    required: false
  filter:
    default: ""
    description: |
      Vale filter that allows you to report an arbitrary subset of the Grafana style.

      For more information, refer to https://vale.sh/docs/filters.
  token:
    default: ${{ github.token }}
    description: Used by reviewdog to comment on pull requests.
    required: false
runs:
  using: composite
  steps:
    - id: changed-files
      if: ${{ ! contains(github.event.pull_request.body, '<!-- vale = NO -->') }}
      uses: tj-actions/changed-files@d6e91a2266cdb9d62096cebf1e8546899c6aa18f # v45.0.6
      with:
        files: ${{ inputs.directory }}/*
    - name: Vale
      if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        DIRECTORY: ${{ inputs.directory }}
        FILTER: --filter=${{ inputs.filter }}
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.token }}
      run: |
          (cd /etc/vale && vale sync)
          vale "${FILTER}" --output=/etc/vale/rdjsonl.tmpl ${ALL_CHANGED_FILES} | \
            inhibit-rules | \
            /bin/reviewdog \
            --conf=/etc/vale/.reviewdog.yml \
            --fail-on-error \
            --f=rdjsonl \
            --name=vale \
            --reporter=github-pr-review
      shell: sh
