name: Run Vale
description: |
  Lints documentation with Vale.

  Note that the action assumes you are running the steps using the grafana/vale container image.
inputs:
  directory:
    default: docs/sources
    description: Directory containing documentation for linting.
    required: false
  filter:
    default: ""
    description: |
      Vale filter that allows you to report an arbitrary subset of the Grafana style.

      For more information, refer to https://vale.sh/docs/filters.
  fail_on_error:
    default: "false"
    description: |
      Exit with a non-zero status code if Vale reports any linting errors.

      Set to 'true' to fail the workflow when linting errors are present.
runs:
  using: composite
  steps:
    - name: Get changed files
      if: github.event_name == 'pull_request' && ! contains(github.event.pull_request.body, '<!-- vale = NO -->')
      id: changed-files
      uses: step-security/changed-files@2e07db73e5ccdb319b9a6c7766bd46d39d304bad # v47.0.5
      with:
        files: |
          ${{ inputs.directory }}/**/*.md

    - run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"
      shell: sh

    - name: Run Vale on pull request
      if: github.event_name == 'pull_request' && ! contains(github.event.pull_request.body, '<!-- vale = NO -->')
      env:
        FILES: ${{ steps.changed-files.outputs.all_changed_files || inputs.directory }}
        FILTER: ${{ inputs.filter }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        if [ -n "${RUNNER_DEBUG+x}" ]; then
          set -x
        fi

        filter_arg=""
        if [ -n "${FILTER}" ]; then
          filter_arg="--filter=${FILTER}"
        fi

        (cd /etc/vale && vale sync)
        vale ${filter_arg:+"${filter_arg}"} --no-exit --output=line ${FILES}
        vale ${filter_arg:+"${filter_arg}"} --no-exit --output=JSON ${FILES} > vale.json
      shell: sh

    - name: Post inline PR review comments
      if: github.event_name == 'pull_request' && ! contains(github.event.pull_request.body, '<!-- vale = NO -->')
      env:
        FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        script: |
          const script = require(`${process.env.GITHUB_ACTION_PATH}/report-vale.js`);
          await script({ context, core, github });
