name: Run Vale
description: |
  Lints documentation with Vale.

  Note that the action assumes you are running the steps using the grafana/vale container image.
inputs:
  directory:
    default: docs/sources
    description: Directory containing documentation for linting.
    required: false
  filter:
    default: ""
    description: |
      Vale filter that allows you to report an arbitrary subset of the Grafana style.

      For more information, refer to https://vale.sh/docs/filters.
runs:
  using: composite
  steps:
    - name: Get changed files
      id: changed-files
      uses: step-security/changed-files@3dbe17c78367e7d60f00d78ae6781a35be47b4a1 # v45.0.1
      with:
        files: |
          ${{ inputs.directory }}/**.md

    - run: git config --global --add safe.directory /__w/writers-toolkit/writers-toolkit
      shell: sh

    - name: Vale
      if: ${{ ! contains(github.event.pull_request.body, '<!-- vale = NO -->') }}
      env:
        FILES: ${{ steps.changed-files.all_changed_files }}
        FILTER: --filter=${{ inputs.filter }}
      run: |
          (cd /etc/vale && vale sync)
          vale "${FILTER}" --output=/etc/vale/sarif.tmpl ${FILES} > vale.sarif
      shell: sh

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@5f8171a638ada777af81d42b55959a643bb29017 # v3.28.12
      with:
        sarif_file: vale.sarif
        category: Vale
