name: Run Vale
description: |
  Lints documentation with Vale.

  Note that the action assumes you are running the steps using the grafana/vale container image.
inputs:
  directory:
    default: docs/sources
    description: Directory containing documentation for linting.
    required: false
  filter:
    default: ""
    description: |
      Vale filter that allows you to report an arbitrary subset of the Grafana style.

      For more information, refer to https://vale.sh/docs/filters.
runs:
  using: composite
  steps:
    - name: Get changed files
      if: github.event == 'pull_request' && ! contains(github.event.pull_request.body, '<!-- vale = NO -->')
      id: changed-files
      uses: step-security/changed-files@3dbe17c78367e7d60f00d78ae6781a35be47b4a1 # v45.0.1
      with:
        files: ${{ inputs.directory }}/**

    - run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"
      shell: sh

    - name: Vale
      if: "! contains(github.event.pull_request.body, '<!-- vale = NO -->')"
      env:
        FILES: ${{ steps.changed-files.outputs.all_changed_files || inputs.directory }}
        FILTER: --filter=${{ inputs.filter }}
      run: |
        if [ -n "${RUNNER_DEBUG+x}" ]; then
          set -x
        fi

        (cd /etc/vale && vale sync)
        vale "${FILTER}" --output=/etc/vale/sarif.tmpl ${FILES} > vale.sarif

        if [ -n "${RUNNER_DEBUG+x}" ]; then
          cat vale.sarif
        fi
      shell: sh

    - name: Upload SARIF file
      if: failure()
      uses: github/codeql-action/upload-sarif@1b549b9259bda1cb5ddde3b41741a82a2d15a841 # v3.28.13
      with:
        sarif_file: vale.sarif
        category: Vale
