worker_processes 1;
pid run/nginx.pid;
worker_rlimit_nofile 8192;

events {
  worker_connections 4096;
}

http {
  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;
  keepalive_timeout 65;
  types_hash_max_size 2048;

  default_type application/octet-stream;

  access_log access.log;
  error_log error.log;

  gzip on;
  gzip_vary on;
  gzip_proxied any;
  gzip_comp_level 6;
  gzip_buffers 16 8k;
  gzip_http_version 1.1;
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml;

  server {
    absolute_redirect off;

    listen 80;

    include /etc/nginx/build.conf;

    add_header Cache-Control "public, max-age=0, must-revalidate";
    add_header X-Frame-Options "DENY";
    add_header 'Access-Control-Allow-Origin' '*';
    add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
    add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
    add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';

    error_page 404 /404.html;
    error_page 403 /404.html;
    location = /404.html {
      root dist/;
      internal;
    }

    location ~* ^/static/(app.min.css|app.css.map|shared.min.css|shared.css.map|.*.json|.*.html|.*.js|lastmod.csv)$ {
      alias dist/static/$1;
    }

    location / {
      alias dist/;
    }

    include /etc/nginx/locations.conf;
  }
}
