"exceptions":
  - "ADOT"
  - "API"
  - "APT"
  - "ARN"
  - "AWS"
  - "BPF"
  - "CLI"
  - "CORS"
  - "CPU"
  - "CRD"
  - "CSS"
  - "CSV"
  - "DNS"
  - "DOM"
  - "eBPF"
  - "FAQ"
  - "GNU"
  - "GPG"
  - "GPU"
  - "GUI"
  - "HTML"
  - "HTTP"
  - "HTTPS"
  - "IBM"
  - "IDE"
  - "JAR"
  - "JPG"
  - "JSON"
  - "JSX"
  - "LESS"
  - "NAT"
  - "OSS"
  - "OTLP"
  - "PDF"
  - "PHP"
  - "PNG"
  - "RAM"
  - "RBAC"
  - "REPL"
  - "RHEL"
  - "RPM"
  - "RSA"
  - "SCM"
  - "SCSS"
  - "SDK"
  - "SEO"
  - "SHA-1"
  - "SQL"
  - "SSD"
  - "SSM"
  - "SSH"
  - "SSL"
  - "SSO"
  - "SUSE"
  - "SVG"
  - "TCP"
  - "TLS"
  - "TSDB"
  - "UI"
  - "UID"
  - "URI"
  - "URL"
  - "USB"
  - "UTC"
  - "UTF"
  - "UUID"
  - "UX"
  - "VPC"
  - "XML"
  - "YAML"
  - "ZIP"
"extends": "conditional"
"first": "\\b([A-Z]{3,5})\\b"
"ignorecase": false
"level": "suggestion"
"link": "https://developers.google.com/style/abbreviations"
"message": "Spell out '%s', if it's unfamiliar to the audience. To spell out the abbreviation, you must enclose the full spelling and the abbreviation in parentheses, with italic emphasis. For example, _application programming interface (API)_."
"scope": "raw"
"second": "_(?:[A-Za-z][a-z]+ )+\\(([A-Z]{3,5})\\)_"
