action:
  name: remove
extends: existence
level: warning
link: https://developers.google.com/style/tone#some-things-to-avoid-where-possible
message: |
  Remove the exclamation point.

  Exclamation points make technical documentation feel informal and hyperbolic.
nonword: true
tokens:
  - "\\w+!(?:\\s|$)"
