extends: spelling
message: |
  '%s' is not in the Grafana dictionary.

  If the word is correct, add it to the dictionary by following [Add words to the Grafana Labs dictionary](https://grafana.com/docs/writers-toolkit/review/lint-prose/dictionary/add-words/).
  Alternatively, raise an [issue](https://github.com/grafana/writers-toolkit/issues/new?title=Grafana.Spelling%%3A%%20%[1]s) and a maintainer will add it for you.

  The spell checker ignores words in the following formatting:
  - [Bold](https://grafana.com/docs/writers-toolkit/write/style-guide/style-conventions/#bold) — use for UI elements.
  - [Code](https://grafana.com/docs/writers-toolkit/write/style-guide/style-conventions/#code-font) — use for paths, configuration, user input, code, class, method, and variable names, status codes, and console output.
level: error
append: true
dicpath: config/dictionaries
dictionaries:
  - en_US-grafana
  - en_US-places
