"action":
  "name": "edit"
  "params":
    - "replace"
    - "-"
    - " "
"extends": "existence"
"ignorecase": false
"level": "error"
"link": "https://developers.google.com/style/hyphens"
"message": "'%s' doesn't need a hyphen."
"nonword": true
"tokens":
  - "\\s[^\\s-]+ly-"
