name: build-website
description: |
  Build the website using the container image and local documentation sources.

inputs:
  command:
    default: make hugo
    description: Command and arguments to run to verify the website builds.
  image:
    default: grafana/docs-base:latest
    description: Container image to run.
  source_directory:
    default: docs/sources
    description: Path to source directory, relative to the project root, to sync documentation from.
  website_directory:
    description: Website directory to sync the documentation to.
    required: true

runs:
  using: composite
  steps:
    - name: Build website
      env:
        COMMAND: ${{ inputs.command }}
        IMAGE: ${{ inputs.image }}
        SOURCE_DIRECTORY: ${{ inputs.source_directory }}
        WEBSITE_DIRECTORY: ${{ inputs.website_directory }}
      run: |
        docker run -v "${PWD}/${SOURCE_DIRECTORY}:/hugo/${WEBSITE_DIRECTORY}" --rm "${IMAGE}" /bin/bash -c "${COMMAND}"
      shell: bash
