version: "2"
linters:
  default: all
  disable:
    - lll
  settings:
    cyclop:
      max-complexity: 12
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/grafana/killercoda/tools/transformer/goldmark
            - github.com/grafana/killercoda/tools/transformer/killercoda
            - github.com/grafana/killercoda/tools/transformer/parser
            - github.com/yuin/goldmark
            - github.com/yuin/goldmark/ast
            - github.com/yuin/goldmark-meta
n            - github.com/yuin/goldmark/extension
            - github.com/yuin/goldmark/parser
            - github.com/yuin/goldmark/renderer
            - github.com/yuin/goldmark/renderer/html
            - github.com/yuin/goldmark/text
            - github.com/yuin/goldmark/util
            - mvdan.cc/xurls/v2
            - github.com/stretchr/testify/assert
            - github.com/stretchr/testify/require
    funlen:
      ignore-comments: true
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - NodeRenderer
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
    varnamelen:
      ignore-names:
        - b
        - err
        - fi
        - f
        - i
        - j
        - md
        - "n"
        - tc
        - u
        - w
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
