location /static {
  proxy_pass https://grafana.com/static;
}

location /media {
  proxy_pass https://grafana.com/media;
}

location /api {
  proxy_pass https://grafana.com/api;
}

location ~ ^/(web|grafana|help|community|blog|products|oss|events|tutorials|whats-new|contact|login|developers|profile|orgs|legal|tutorials|signup|pricing|enterprise|accessibility|assets|about)(/.*)?$ {
  proxy_pass https://grafana.com;
}

location ~ ^/connect(.*)$ {

  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header Host $http_host;
  proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;

  proxy_ssl_server_name on;
  resolver          8.8.8.8 8.8.4.4 ipv6=off;
  resolver_timeout  5s;
  set $faro "faro-collector-prod-us-central-0.grafana.net";

  proxy_pass https://$faro/collect$1;
}

location /healthz {
  return 200 'ok';
  add_header Content-Type text/plain;
}
