name: Backport PR creator
on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  main:
    if:  ${{ github.repository == 'grafana/writers-toolkit' }}
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@main
        with:
          common_secrets: |
            ISSUE_COMMANDS_APP_ID=docs-team/issue-commands:app-id
            ISSUE_COMMANDS_PRIVATE_KEY=docs-team/issue-commands:key
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ env.ISSUE_COMMANDS_APP_ID }}
          private-key: ${{ env.ISSUE_COMMANDS_PRIVATE_KEY }}
      - name: Checkout Actions
        uses: actions/checkout@v4
        with:
          repository: grafana/grafana-github-actions
          path: ./actions
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run backport
        uses: ./actions/backport
        with:
          token: ${{ steps.app-token.outputs.token }}
          labelsToAdd: backport
          title: "[{{base}}] {{originalTitle}}"
