name: Deploy pr preview

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    paths:
      - "docs/sources/**"

concurrency:
  group: ${{ github.workflow }}-${{ inputs.repo }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy-pr-preview:
    if: ${{ ! github.event.pull_request.head.repo.fork }}
    permissions:
      contents: read
      id-token: write # Fetch Vault secrets.
      pull-requests: write # Create or update PR comments.
      statuses: write # Update GitHub status check with deploy preview link.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - uses: ./deploy-preview
        with:
          branch: ${{ github.head_ref }}
          event_number: ${{ github.event.number }}
          sha: ${{ github.event.pull_request.head.sha }}
          sources: |
            [{
                "index_file": null,
                "relative_prefix": "/docs/writers-toolkit/",
                "source_directory": "docs/sources",
                "website_directory": "content/docs/writers-toolkit"
            }]
          title: ${{ github.event.pull_request.title }}
