name: Deploy pr preview

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    paths:
      - "docs/sources/**"

jobs:
  deploy-pr-preview:
    uses: grafana/writers-toolkit/.github/workflows/deploy-preview.yml@robbymilo/deploy-preview
    if: "!github.event.pull_request.head.repo.fork"
    with:
      branch: ${{ github.head_ref }}
      event_number: ${{ github.event.number }}
      repo: writers-toolkit
      sha: ${{ github.event.pull_request.head.sha }}
      sources: |
        [{
            "index_file": null,
            "relative_prefix": "/docs/writers-toolkit/",
            "repo": "writers-toolkit",
            "source_directory": "docs/sources",
            "website_directory": "content/docs/writers-toolkit"
        }]
      title: ${{ github.event.pull_request.title }}
