name: Publish grafana/vale image

permissions: {}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.repository == 'grafana/writers-toolkit' }}
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - id: push-to-dockerhub
        uses: grafana/shared-workflows/actions/docker-build-push-image@21ae57f82e5256e5a418406388926d4ba24bccf2 # docker-build-push-image/v0.3.2
        with:
          context: vale
          platforms: linux/amd64,linux/arm64
          push: true
          dockerhub-repository: grafana/vale
          registries: dockerhub
          tags: |-
            ${{ github.sha }}
            latest
