name: Run `prettier` on a branch
on:
  workflow_dispatch:
    inputs:
      path:
        default: docs/sources
        description: Path to run `prettier` on.
        type: string
jobs:
  prettier:
    permissions:
      contents: read
      id-token: write
    if: ${{ github.repository == 'grafana/writers-toolkit' }}
    runs-on: ubuntu-latest
    steps:
      - uses: grafana/writers-toolkit/prettier@jdb/2025-04-use-docs-platform-github-app
        with:
          branch: ${{ env.GITHUB_REF }}
          path: ${{ inputs.path }}
