name: Run `prettier` on a branch

permissions: {}

on:
  workflow_dispatch:
    inputs:
      path:
        default: docs/sources
        description: Path to run `prettier` on.
        type: string

jobs:
  prettier:
    permissions:
      contents: read
      id-token: write
    if: github.repository == 'grafana/writers-toolkit'
    runs-on: ubuntu-latest
    steps:
      - uses: grafana/writers-toolkit/prettier@main # zizmor: ignore[unpinned-uses] It's a protected branch in the same repository.
        with:
          branch: ${{ env.GITHUB_REF }}
          path: ${{ inputs.path }}
