name: Run `prettier` on a branch
on:
  workflow_dispatch:
jobs:
  prettier:
    if: ${{ github.repository == 'grafana/writers-toolkit' }}
    runs-on: ubuntu-latest
    steps:
      - uses: grafana/writers-toolkit/prettier@91670afefdef8a5e06b979b3b15bf823984dccee # prettier/v2.0.1
        with:
          branch: ${{ env.GITHUB_REF }}
