name: Run `prettier` on a branch
on:
  workflow_dispatch:
jobs:
  prettier:
    if: ${{ github.repository == 'grafana/writers-toolkit' }}
    runs-on: ubuntu-latest
    steps:
      - uses: grafana/writers-toolkit/prettier@jdb/2025-04-use-docs-platform-github-app
        with:
          branch: ${{ env.GITHUB_REF }}
