name: Run `prettier` on a branch
on:
  workflow_dispatch:
jobs:
  prettier:
    if: ${{ github.repository == 'grafana/writers-toolkit' }}
    runs-on: ubuntu-latest
    steps:
      - uses: grafana/writers-toolkit/prettier@c5e0c5cdbacb866aff36cc7747db7d49d9de2588 # prettier/v2.0.1
        with:
          branch: ${{ env.GITHUB_REF }}
