name: Run `prettier` on a branch
on:
  workflow_dispatch:
    inputs:
      trace:
        default: false
        description: Print command traces?
        required: false
        type: boolean
jobs:
  prettier:
    if:  ${{ github.repository == 'grafana/writers-toolkit' }}
    runs-on: ubuntu-latest
    steps:
      - uses: ./prettier
        with:
          branch: ${{ env.GITHUB_REF }}
          trace: ${{ inputs.trace }}
