name: Run `prettier` on a branch
on:
  workflow_dispatch:
jobs:
  prettier:
    if: ${{ github.repository == 'grafana/writers-toolkit' }}
    runs-on: ubuntu-latest
    steps:
      - uses: grafana/writers-toolkit/prettier@eb7770256e7ee6fb32b36261f0d12a33850515f1 # prettier/v2.0.1
        with:
          branch: ${{ env.GITHUB_REF }}
