name: Lint prose with Vale
on:
  issue_comment:
    types: [created]
jobs:
  vale:
    if: ${{ github.event.issue.pull_request && github.event.issue.state == 'open' && contains(github.event.comment.body, '/vale') }}
    runs-on: ubuntu-latest
    container:
      image: grafana/vale:latest@sha256:55bf7dcba4ceac896b55225084bdb0b27e2e2f70c1398313bee13cb45eb60a95
    steps:
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          # Not a separate file because then it doesn't have to wait for a checkout to be run.
          script: |
            await github.request('POST /repos/{owner}/{repo}/issues/comments/{comment_id}/reactions', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'eyes',
            });
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          ref: refs/pull/${{ github.event.issue.number }}/head

      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        id: from-comment
        with:
          script: |
            const script = require('./.github/workflows/from-comment.js');

            await script({ core, context, github });

      - name: Run linter
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TO_LINT: ${{ steps.from-comment.outputs.to-lint }}
        run: echo "${TO_LINT}"
